"""Label the true material of every region of a classification run, by hand.

Produces ground_truth.csv, which evaluate.py scores any run against. One
keypress per region; the window shows the region zoomed on the left and where
it sits in the frame on the right.

The prediction is hidden
------------------------
The run's own answer is NOT shown while labelling, by default. If the screen
says "glass 0.94" while you decide, you will agree with it more often than you
should, and a ground truth that was anchored on the thing it is meant to judge
measures nothing. --show-prediction exists for reviewing a finished pass, not
for making one.

One pass per SEGMENTER, not per run
-----------------------------------
Region ids are positional. A ground-truth row means "region 3 of this frame",
which is only the same patch of image in runs that share a labels.npy. Prior
on/off pairs do share one (segmentation happens first, independently of the
prior), so one pass covers both sides of that comparison. SAM and Mask2Former
do not, so comparing those needs a second pass over the same photographs --
which is why the frame set is pinned in eval_frames.txt rather than sampled per
run. gt_common.assert_compatible enforces all of this at scoring time; nothing
here has to be remembered.

Usage:
    # once: pin the eval frames
    py annotate.py --init-frames --run ...\\fullrate\\material_map_m2f --n 20

    # then label
    py annotate.py --session-dir ...\\ZED\\20260730_161223\\fullrate \\
                   --run ...\\fullrate\\material_map_m2f \\
                   --out ground_truth_m2f.csv

Quit any time with Esc; relaunching resumes at the first unlabelled region.
"""

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))

import gt_common as gt                                            # noqa: E402

# Digits first, then letters, skipping the two the statuses own.
KEY_POOL = "1234567890abcdefghijklnoprstvwxyz"
KEY_MIXED, KEY_UNCLEAR = "m", "u"

# Materials in the order they should get the easy keys. Purely ergonomic: the
# common indoor surfaces land on the digits and the bare metals -- which the
# category prior makes nearly unreachable anyway -- end up on letters. Anything
# in the table but missing here still gets a key, appended in table order, so
# an emissivity_table.csv edit can never leave a material unbindable.
PREFERRED = [
    "paint", "plaster", "concrete", "brick", "wood",
    "glass", "ceramic", "plastic", "rubber", "fabric",
    "painted_metal", "cardboard", "asphalt",
]


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def build_keymap(materials: list[str]) -> dict[str, str]:
    """key -> material, deterministic and complete."""
    ordered = [m for m in PREFERRED if m in materials]
    ordered += [m for m in materials if m not in ordered]
    if len(ordered) > len(KEY_POOL):
        raise ValueError(f"{len(ordered)} materials but only {len(KEY_POOL)} keys.")
    return {KEY_POOL[i]: m for i, m in enumerate(ordered)}


def init_frames(run_dir: Path, n: int, out: Path, stride: int) -> None:
    """Pin the eval frame set, as a stride so the runs can be regenerated.

    stems[::stride][:n] rather than an even spread, because neither classifier
    has a --frames flag: classify_session.py and classify_session_m2f.py can
    only subset with --every-n and --limit. A stride is therefore reproducible
    on the regeneration side with no edit to either of them.
    """
    stems = sorted(p.name for p in Path(run_dir).iterdir() if p.is_dir())
    if not stems:
        raise SystemExit(f"No frame subdirectories in {run_dir}.")
    picked = stems[::stride][:n]
    if len(picked) < n:
        raise SystemExit(
            f"{run_dir} has {len(stems)} frames; stride {stride} yields only "
            f"{len(picked)}, not {n}. Lower --stride or --n.")

    out.write_text(
        f"# Eval frame set -- {len(picked)} FLIR stems, pinned.\n"
        f"# Generated by annotate.py --init-frames from {Path(run_dir).name} "
        f"({len(stems)} frames).\n"
        f"# Rule: sorted(stems)[::{stride}][:{n}]  -- a stride, not an even spread,\n"
        f"# so the runs can be regenerated to cover exactly these frames with:\n"
        f"#     --every-n {stride} --limit {n}\n"
        f"# Every run and BOTH segmenters must use this same set: comparing SAM to\n"
        f"# Mask2Former means labelling the same photographs twice, once each.\n"
        + "\n".join(picked) + "\n", encoding="utf-8")
    print(f"Wrote {out} with {len(picked)} frames ({picked[0]} .. {picked[-1]}).")
    print(f"Regenerate runs over exactly these with: --every-n {stride} --limit {n}")


def region_bbox(mask: np.ndarray) -> tuple[int, int, int, int]:
    """(x0, y0, x1, y1) from the mask itself.

    Not from segments.json: the oldest run on disk (classify_session.py,
    material_map/) writes no bbox key at all, only centroid_px and area_px. The
    mask is the authoritative extent anyway.
    """
    ys, xs = np.nonzero(mask)
    return int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1


def _to_photo(arr: np.ndarray, box_w: int, box_h: int):
    """Fit an RGB array into box_w x box_h, letterboxed, as a Tk image."""
    from PIL import Image, ImageTk

    h, w = arr.shape[:2]
    scale = min(box_w / w, box_h / h)
    nw, nh = max(1, int(w * scale)), max(1, int(h * scale))
    # NEAREST when magnifying so a small region shows its actual pixels rather
    # than an interpolated guess at them; LANCZOS when shrinking.
    resample = Image.NEAREST if scale > 1.5 else Image.LANCZOS
    return ImageTk.PhotoImage(Image.fromarray(arr).resize((nw, nh), resample))


def render_region(image: np.ndarray, mask: np.ndarray, pad_frac: float = 0.35):
    """Zoomed crop around the region, everything outside the mask dimmed.

    Dimmed, not blacked out: a thin window reveal is only identifiable from
    what is beside it, and a hard black surround also drags the eye toward
    reading the region as dark-coloured. The padding is what supplies that
    context -- the bbox alone can be flush with the object.
    """
    x0, y0, x1, y1 = region_bbox(mask)
    pad = int(max(x1 - x0, y1 - y0) * pad_frac) + 8
    h, w = image.shape[:2]
    cx0, cy0 = max(0, x0 - pad), max(0, y0 - pad)
    cx1, cy1 = min(w, x1 + pad), min(h, y1 + pad)

    crop = image[cy0:cy1, cx0:cx1].astype(np.float32)
    m = mask[cy0:cy1, cx0:cx1]
    dim = (crop * 0.35 + 60.0)                       # toward mid-grey, not black
    out = np.where(m[..., None], crop, dim).astype(np.uint8)

    # A one-pixel outline, so the exact boundary stays readable where the
    # region and its surroundings are the same colour. Marks every pixel whose
    # right or lower neighbour is on the other side of the mask.
    b = np.zeros_like(m)
    b[:-1, :] |= m[:-1, :] ^ m[1:, :]
    b[:, :-1] |= m[:, :-1] ^ m[:, 1:]
    out[b] = (255, 60, 60)
    return out


def render_context(image: np.ndarray, mask: np.ndarray):
    """Whole frame, region tinted, so you can see WHICH object this is."""
    out = image.astype(np.float32)
    tint = np.array([255.0, 60.0, 60.0])
    out[mask] = out[mask] * 0.45 + tint * 0.55
    return out.astype(np.uint8)


class Annotator:
    def __init__(self, args, materials, keymap, todo, rows, out_path, session):
        import tkinter as tk

        self.args, self.materials, self.keymap = args, materials, keymap
        self.todo = todo                     # [(frame, RunFrame, seg), ...]
        self.rows = rows                     # existing + new ground-truth rows
        self.done = {(r["frame"], r["region_id"]) for r in rows}
        self.out_path, self.session = out_path, session
        self.images = {}                     # frame -> ZED RGB array
        self.i = 0

        self.tk = tk
        self.root = tk.Tk()
        self.root.title(f"annotate.py -- {Path(args.run).name}")
        self.root.configure(bg="#1e1e1e")

        self.header = tk.Label(self.root, font=("Consolas", 13), bg="#1e1e1e",
                               fg="#eaeaea", anchor="w", justify="left")
        self.header.grid(row=0, column=0, columnspan=2, sticky="we", padx=10, pady=(8, 4))

        self.left = tk.Label(self.root, bg="#111111")
        self.left.grid(row=1, column=0, padx=(10, 5), pady=5)
        self.right = tk.Label(self.root, bg="#111111")
        self.right.grid(row=1, column=1, padx=(5, 10), pady=5, sticky="n")

        self.legend = tk.Label(self.root, font=("Consolas", 10), bg="#1e1e1e",
                               fg="#bdbdbd", anchor="w", justify="left")
        self.legend.grid(row=2, column=0, columnspan=2, sticky="we", padx=10, pady=(4, 2))
        self.legend.configure(text=self.legend_text())

        self.status = tk.Label(self.root, font=("Consolas", 11), bg="#1e1e1e",
                               fg="#8ec07c", anchor="w")
        self.status.grid(row=3, column=0, columnspan=2, sticky="we", padx=10, pady=(0, 8))

        self.root.bind("<Key>", self.on_key)
        self.root.bind("<Escape>", lambda e: self.quit())
        self.root.bind("<Right>", lambda e: self.advance(1))
        self.root.bind("<Left>", lambda e: self.advance(-1))
        self.root.protocol("WM_DELETE_WINDOW", self.quit)

    def legend_text(self) -> str:
        items = [f"[{k}] {m}" for k, m in self.keymap.items()]
        items += [f"[{KEY_MIXED}] MIXED", f"[{KEY_UNCLEAR}] UNCLEAR"]
        cols = 5
        rows = (len(items) + cols - 1) // cols
        grid = []
        for r in range(rows):
            grid.append("  ".join(f"{items[r + c * rows]:<22}"
                                  for c in range(cols) if r + c * rows < len(items)))
        return "\n".join(grid) + "\n← back   → skip   Esc quit"

    def image_for(self, frame: str, rf) -> np.ndarray:
        if frame not in self.images:
            from PIL import Image
            name = rf.source_zed_frame
            if not name:
                raise SystemExit(f"{frame}: segments.json has no source_zed_frame.")
            path = self.frames_dir / name
            if not path.exists():
                raise SystemExit(f"{frame}: ZED image {path} does not exist.")
            self.images = {}                 # one frame at a time; these are 6 MB each
            self.images[frame] = np.asarray(Image.open(path).convert("RGB"))
        return self.images[frame]

    def current(self):
        return self.todo[self.i]

    def show(self):
        frame, rf, seg = self.current()
        image = self.image_for(frame, rf)
        mask = rf.mask(seg["id"])

        self.photo_l = _to_photo(render_region(image, mask), 720, 620)
        self.photo_r = _to_photo(render_context(image, mask), 470, 264)
        self.left.configure(image=self.photo_l)
        self.right.configure(image=self.photo_r)

        n_frames = len({f for f, _, _ in self.todo})
        seen = len({f for f, _, _ in self.todo[:self.i + 1]})
        ade = seg.get("ade")
        head = (f"frame {seen}/{n_frames}  {frame}          "
                f"region {seg['id']}   area {seg['area_px']:,} px")
        if ade:
            head += f"   ade={ade}"
        if self.args.show_prediction:
            head += (f"\nPREDICTION SHOWN: {seg['top_material']} "
                     f"{seg['confidence']:.2f}   (biases labelling -- review only)")
        prev = self.label_of(frame, seg["id"])
        if prev:
            head += f"\nalready labelled: {prev}   (press a key to change)"
        self.header.configure(text=head)

        n_done = len(self.done)
        self.status.configure(
            text=f"{self.i + 1}/{len(self.todo)} shown    {n_done} saved    "
                 f"{len(self.todo) - n_done} left    -> {self.out_path.name}")

    def label_of(self, frame, rid):
        for r in self.rows:
            if r["frame"] == frame and r["region_id"] == rid:
                return r["ground_truth"] or r["status"]
        return None

    def record(self, status: str, material: str):
        frame, rf, seg = self.current()
        self.rows = [r for r in self.rows
                     if not (r["frame"] == frame and r["region_id"] == int(seg["id"]))]
        self.rows.append({
            "session": self.session,
            "run_used": Path(self.args.run).name,
            "frame": frame,
            "region_id": int(seg["id"]),
            "area_px": int(seg["area_px"]),
            "ade": seg.get("ade", ""),
            "status": status,
            "ground_truth": material,
            "labels_md5": rf.md5,
            "annotated_utc": utc_now_iso(),
        })
        self.done.add((frame, int(seg["id"])))
        # After every single label: an hour of work must not depend on a clean exit.
        gt.write_ground_truth(self.out_path, self.sorted_rows())
        self.advance(1)

    def sorted_rows(self):
        order = {f: i for i, f in enumerate(dict.fromkeys(f for f, _, _ in self.todo))}
        return sorted(self.rows, key=lambda r: (order.get(r["frame"], 1e9), r["region_id"]))

    def advance(self, step: int):
        self.i += step
        if self.i >= len(self.todo):
            print(f"\nReached the end. {len(self.done)} region(s) recorded.")
            return self.quit()
        self.i = max(0, self.i)
        self.show()

    def on_key(self, event):
        k = event.char.lower()
        if k in self.keymap:
            self.record(gt.LABELED, self.keymap[k])
        elif k == KEY_MIXED:
            self.record("mixed", "")
        elif k == KEY_UNCLEAR:
            self.record("unclear", "")

    def quit(self):
        gt.write_ground_truth(self.out_path, self.sorted_rows())
        print(f"Saved {len(self.done)} labelled region(s) to {self.out_path}")
        self.root.destroy()

    def run(self, frames_dir: Path):
        self.frames_dir = frames_dir
        self.show()
        self.root.mainloop()


def parse_args():
    p = argparse.ArgumentParser(
        description="Hand-label the true material of each region of a "
                    "material_map/v1 run, for evaluate.py to score against.")
    p.add_argument("--run", required=True, metavar="DIR",
                   help="The run whose labels.npy defines the regions "
                        "(e.g. ...\\fullrate\\material_map_m2f). Its own predictions "
                        "are NOT shown unless --show-prediction.")
    p.add_argument("--session-dir", metavar="DIR",
                   help="ZED session folder holding metadata.json + frames/. Required "
                        "unless --init-frames.")
    p.add_argument("--frames", default=None, metavar="TXT",
                   help=f"Eval frame list (default {gt.DEFAULT_FRAMES.name}).")
    p.add_argument("--out", default="ground_truth.csv", metavar="CSV",
                   help="Output ground truth (default ground_truth.csv). Use a "
                        "per-segmenter name, e.g. ground_truth_m2f.csv.")
    p.add_argument("--table", default=None, metavar="CSV",
                   help="Alternative emissivity_table.csv (defines the label choices).")
    p.add_argument("--min-area", type=int, default=0, metavar="PX",
                   help="Regions smaller than this are recorded as 'unclear' without "
                        "being shown (default 0 = show everything). SAM's smallest "
                        "region on this session is 3 px, which cannot be judged.")
    p.add_argument("--show-prediction", action="store_true",
                   help="Show the run's own material while labelling. OFF by default, "
                        "deliberately: seeing the answer makes you agree with it, and "
                        "a ground truth anchored on the thing it judges is worthless. "
                        "For reviewing a finished pass.")
    p.add_argument("--redo", action="store_true",
                   help="Revisit regions already present in --out instead of skipping them.")
    p.add_argument("--init-frames", action="store_true",
                   help="Write the pinned eval frame list from --run and exit.")
    p.add_argument("--n", type=int, default=20, metavar="N",
                   help="How many frames --init-frames pins (default 20).")
    p.add_argument("--stride", type=int, default=5, metavar="N",
                   help="--init-frames takes every Nth frame (default 5), so the set "
                        "is reproducible as --every-n N --limit <n> when the runs are "
                        "regenerated.")
    return p.parse_args()


def main():
    args = parse_args()
    run_dir = Path(args.run)
    frames_path = Path(args.frames) if args.frames else gt.DEFAULT_FRAMES

    if args.init_frames:
        init_frames(run_dir, args.n, frames_path, args.stride)
        return 0

    if not args.session_dir:
        print("--session-dir is required (it holds metadata.json + frames/).",
              file=sys.stderr)
        return 1
    session_dir = Path(args.session_dir)

    materials, _eps = gt.load_material_table(args.table)
    keymap = build_keymap(materials)
    frames = gt.load_eval_frames(frames_path)
    frames_dir = gt.load_zed_frames_dir(session_dir)

    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = _HERE / out_path
    rows = gt.read_ground_truth(out_path) if out_path.exists() else []

    # Guard against pointing a second pass at the first pass's file: the rows
    # would silently mix two segmentations, and every md5 check downstream
    # would then fail on whichever half did not match.
    other = {r["run_used"] for r in rows} - {run_dir.name}
    if other:
        print(f"{out_path.name} already holds rows annotated on {sorted(other)}, "
              f"not {run_dir.name}. Region ids are not comparable between "
              f"segmenters -- use a separate file for this run.", file=sys.stderr)
        return 1

    print(f"Loading {len(frames)} frame(s) from {run_dir.name} ...")
    todo, auto = [], 0
    done = {(r["frame"], r["region_id"]) for r in rows}
    for f in frames:
        rf = gt.load_run_frame(run_dir, f)
        for seg in sorted(rf.segments, key=lambda s: int(s["id"])):
            rid = int(seg["id"])
            if not args.redo and (f, rid) in done:
                continue
            if args.min_area and int(seg["area_px"]) < args.min_area:
                rows.append({
                    "session": session_dir.parent.name, "run_used": run_dir.name,
                    "frame": f, "region_id": rid, "area_px": int(seg["area_px"]),
                    "ade": seg.get("ade", ""), "status": "unclear", "ground_truth": "",
                    "labels_md5": rf.md5, "annotated_utc": utc_now_iso(),
                })
                done.add((f, rid))
                auto += 1
                continue
            todo.append((f, rf, seg))

    if auto:
        print(f"{auto} region(s) below --min-area {args.min_area} auto-recorded as unclear.")
    if not todo:
        gt.write_ground_truth(out_path, rows)
        print(f"Nothing left to label. {len(rows)} row(s) in {out_path}.")
        return 0

    print(f"{len(todo)} region(s) to label. Prediction is "
          f"{'SHOWN' if args.show_prediction else 'hidden'}.")
    app = Annotator(args, materials, keymap, todo, rows, out_path,
                    session=session_dir.parent.name)
    app.run(frames_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
